name: app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  inner_drawer: ^1.0.0+1
  dio: ^5.4.0
  geolocator: ^10.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
